---
abstract: 'Build mazes in SVG.'
author:
  - 'G. Wade Johnson <gwadej@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Games-Maze-SVG
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Games::Maze: 1.02
  Test::More: 0
  perl: 5.006
resources:
  repository: https://github.com/gwadej/Games-Maze-SVG.git
version: 0.9
