# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Games-Maze-SVG
version:      0.75
version_from: lib/Games/Maze/SVG.pm
installdirs:  site
requires:
    Carp:                          0
    Games::Maze:                   1.02
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
